meta_product_name: "GRAVY"
meta_title: "Gravy - Because food is better together"
meta_description: "Gravy is the app that gives you the best food in your area. Perhaps not physically, but we give you the truth. By the people, for the people."
meta_image: "Restaurant.jpeg"
twitter_account: "@gravyapp"
